apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cloudnative-pg-operator

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.26/releases/cnpg-1.26.0.yaml

commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/component: operator
  app.kubernetes.io/managed-by: kustomize