apiVersion: v2
name: cloudnative-pg
description: CloudNativePG operator for PostgreSQL on Kubernetes
type: application
version: 0.1.0
appVersion: "1.27.0"

dependencies:
  - name: cloudnative-pg
    version: "0.26.0"
    repository: "https://cloudnative-pg.github.io/charts"