apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: linkding
  labels:
    app: linkding
spec:
  selector:
    app: linkding
  ports:
  - name: http
    port: 80
    targetPort: 9090
  type: ClusterIP