apiVersion: v2
name: ollama
description: Ollama - Get up and running with OpenAI gpt-oss, DeepSeek-R1, Gemma 3 and other models
type: application
version: 0.1.0
dependencies:
  - name: ollama
    version: 1.5.0
    repository: https://helm.otwld.com/