gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host git.127-0-0-1.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.127-0-0-1.nip.io
        OFFLINE_MODE: true
      repository:
        DISABLED_REPO_UNITS: repo.wiki,repo.projects,repo.packages
        DISABLE_STARS: true
        DEFAULT_BRANCH: master
      service.explore:
        DISABLE_USERS_PAGE: true
      actions:
        ENABLED: false
      webhook:
        ALLOWED_HOST_LIST: private