# PostgreSQL Cluster Configuration for Homelab
postgresql:
  # Cluster configuration
  instances: 1
  
  # Database configuration
  database: postgres
  owner: postgres
  
  # Storage configuration
  storage:
    size: 5Gi
    storageClass: local-path
    
  # Resource configuration
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi" 
      cpu: "500m"
      
  # PostgreSQL parameters
  parameters:
    max_connections: "200"
    shared_buffers: "256MB"
    effective_cache_size: "1GB"

# Credentials configuration
credentials:
  username: postgres
  password: homelab123

# MLflow database configuration
mlflow:
  enabled: true
  database: mlflow
  user: mlflow
  password: mlflow123