apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vitess

resources:
- namespace.yaml
- operator.yaml
- 101_initial_cluster.yaml

configMapGenerator:
- name: vitess-schema
  files:
  - create_commerce_schema.sql
- name: vitess-vschema  
  files:
  - vschema_commerce_initial.json