apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.cluster.name }}
    app.kubernetes.io/managed-by: argocd
spec:
  instances: {{ .Values.cluster.instances }}
  primaryUpdateStrategy: {{ .Values.cluster.primaryUpdateStrategy }}
  
  # PostgreSQL configuration
  postgresql:
    parameters:
      {{- range $key, $value := .Values.cluster.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
      
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.cluster.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.cluster.bootstrap.initdb.secret.name }}
      postInitSQL:
        {{- range .Values.cluster.bootstrap.initdb.postInitSQL }}
        - {{ . | quote }}
        {{- end }}
        
  # Storage configuration  
  storage:
    size: {{ .Values.cluster.storage.size }}
    {{- if .Values.cluster.storage.storageClass }}
    storageClass: {{ .Values.cluster.storage.storageClass }}
    {{- end }}
    
  # Resource configuration
  resources:
    requests:
      memory: {{ .Values.cluster.resources.requests.memory }}
      cpu: {{ .Values.cluster.resources.requests.cpu }}
    limits:
      memory: {{ .Values.cluster.resources.limits.memory }}
      cpu: {{ .Values.cluster.resources.limits.cpu }}
      
  # Security context
  postgresUID: {{ .Values.cluster.postgresUID }}
  postgresGID: {{ .Values.cluster.postgresGID }}
    
  # Monitoring configuration
  {{- if .Values.cluster.monitoring.enabled }}
  monitoring:
    enabled: {{ .Values.cluster.monitoring.enabled }}
    disableDefaultQueries: {{ .Values.cluster.monitoring.disableDefaultQueries }}
  {{- end }}