apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.namespace }}
  labels:
    name: {{ .Values.cluster.namespace }}
    app.kubernetes.io/name: {{ .Values.cluster.name }}
    app.kubernetes.io/managed-by: argocd