apiVersion: v1
kind: Secret
metadata:
  name: postgresql-cluster-credentials
  namespace: {{ .Values.cluster.namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "mlflow" | b64enc }}
  password: {{ "mlflow123" | b64enc }}
  # Also include postgres superuser credentials
  postgres-username: {{ "postgres" | b64enc }}
  postgres-password: {{ "homelab123" | b64enc }}