apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.mlflow.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/instance: mlflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
        app.kubernetes.io/instance: mlflow
    spec:
      {{- with .Values.mlflow.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mlflow
        image: "{{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}"
        imagePullPolicy: {{ .Values.mlflow.image.pullPolicy }}
        {{- with .Values.mlflow.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
        - name: MLFLOW_BACKEND_STORE_URI
          value: "postgresql://{{ .Values.mlflow.database.user }}:{{ .Values.mlflow.database.password }}@{{ .Values.mlflow.database.host }}:{{ .Values.mlflow.database.port }}/{{ .Values.mlflow.database.name }}"
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: "s3://{{ .Values.mlflow.minio.bucket }}/artifacts"
        - name: AWS_ACCESS_KEY_ID
          value: "{{ .Values.mlflow.minio.accessKey }}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "{{ .Values.mlflow.minio.secretKey }}"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://{{ .Values.mlflow.minio.host }}:{{ .Values.mlflow.minio.port }}"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        {{- with .Values.mlflow.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing MLflow and dependencies..."
          pip install --no-cache-dir mlflow[extras]==2.18.0 psycopg2-binary boto3
          
          echo "Waiting for database to be ready..."
          until python -c "import psycopg2; psycopg2.connect(host='{{ .Values.mlflow.database.host }}', port={{ .Values.mlflow.database.port }}, user='{{ .Values.mlflow.database.user }}', password='{{ .Values.mlflow.database.password }}', database='{{ .Values.mlflow.database.name }}')" 2>/dev/null; do
            echo "Database not ready, waiting..."
            sleep 5
          done
          
          echo "Starting MLflow tracking server..."
          mlflow server \
            --backend-store-uri postgresql://{{ .Values.mlflow.database.user }}:{{ .Values.mlflow.database.password }}@{{ .Values.mlflow.database.host }}:{{ .Values.mlflow.database.port }}/{{ .Values.mlflow.database.name }} \
            --default-artifact-root s3://{{ .Values.mlflow.minio.bucket }}/artifacts \
            --host 0.0.0.0 \
            --port 5000
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.mlflow.resources | nindent 10 }}
        {{- if .Values.mlflow.persistence.enabled }}
        volumeMounts:
        - name: mlflow-storage
          mountPath: /tmp/mlflow
        {{- end }}
      {{- if .Values.mlflow.persistence.enabled }}
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
      {{- end }}
      {{- with .Values.mlflow.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mlflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mlflow.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}