{{- if .Values.mlflow.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mlflow.persistence.size }}
  {{- if .Values.mlflow.persistence.storageClass }}
  storageClassName: {{ .Values.mlflow.persistence.storageClass }}
  {{- end }}
{{- end }}