apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
  - port: {{ .Values.mlflow.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.mlflow.service.type "NodePort" }}
    nodePort: {{ .Values.mlflow.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow