{{- if .Values.clusters.mlflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-cluster-superuser
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "mlflow" | b64enc }}
  password: {{ "mlflow456" | b64enc }}
{{- end }}