apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-superuser
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "homelab" | b64enc }}
  password: {{ "homelab123" | b64enc }}