apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "admin@homelab.com"
  PGADMIN_DEFAULT_PASSWORD: "changeme123"
  PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
  PGADMIN_CONFIG_LOGIN_BANNER: '"Homelab PostgreSQL Administration"'
  PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "20"