apiVersion: v2
name: minio
description: MinIO object storage for homelab
type: application
version: 0.1.0
dependencies:
  - name: minio
    version: 17.0.21
    repository: https://charts.bitnami.com/bitnami