# MLflow Configuration for Homelab
mlflow:
  # Image configuration
  image:
    repository: python
    tag: "3.11-slim"
    pullPolicy: IfNotPresent

  # Service configuration
  service:
    type: NodePort
    port: 5000
    nodePort: 30500

  # Resources
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m

  # Database configuration
  database:
    host: postgresql-cluster-rw.postgresql-cluster.svc.cluster.local
    port: 5432
    name: mlflow
    user: mlflow
    password: mlflow123

  # MinIO configuration for artifact storage
  minio:
    host: minio.minio.svc.cluster.local
    port: 9000
    bucket: mlflow-artifacts
    accessKey: admin
    secretKey: homelab123

  # Security context for k3d compatibility
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

  # Pod security context
  podSecurityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

  # Replica count
  replicaCount: 1

  # Node selector, tolerations and affinity
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Additional environment variables
  extraEnv: []

  # Persistence for temporary files
  persistence:
    enabled: true
    size: 1Gi
    storageClass: local-path