pgadmin4:
  # Service configuration
  service:
    type: NodePort
    port: 80
    nodePort: 30082

  # pgAdmin configuration
  env:
    # Default admin user
    email: admin@homelab.com
    password: homelab123

  # Persistence configuration
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: local-path

  # Resource configuration
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  # Security context
  securityContext:
    runAsUser: 5050
    runAsGroup: 5050
    fsGroup: 5050

  # Server configuration
  serverDefinitions:
    enabled: true
    servers:
      homelab-postgres:
        Name: "Homelab PostgreSQL"
        Group: "Servers"
        Host: "postgresql-cluster-rw.postgresql-cluster.svc.cluster.local"
        Port: 5432
        MaintenanceDB: "postgres"
        Username: "postgres"
        SSLMode: "prefer"
        Comment: "Main PostgreSQL cluster for homelab"
      mlflow-postgres:
        Name: "MLflow Database"
        Group: "Servers"
        Host: "postgresql-cluster-rw.postgresql-cluster.svc.cluster.local"
        Port: 5432
        MaintenanceDB: "mlflow"
        Username: "mlflow"
        SSLMode: "prefer"
        Comment: "MLflow tracking database"

  # Network policies
  networkPolicy:
    enabled: false
