apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-reconfig-{{ include (print $.Template.BasePath "/config-source.yaml") . | sha256sum | trunc 7 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: gitea-migration
      containers:
        - name: reconfig
          image: bitnami/kubectl:1.28
          env:
            - name: GITEA_HOST
              value: http://gitea-http:3000
            - name: GITEA_REPO_URL
              value: http://gitea-http:3000/ops/homelab.git
          command:
            - sh
            - -c
          args:
            - |
              set -e
              
              echo "Waiting for Gitea repository to be ready..."
              sleep 60
              
              # Check if repository exists in Gitea
              until curl -f -s "$GITEA_HOST/ops/homelab"; do
                echo "Waiting for homelab repository in Gitea..."
                sleep 10
              done
              
              echo "Repository found in Gitea, updating ArgoCD configuration..."
              
              # Update ArgoCD repository configuration
              kubectl patch configmap argocd-cm -n argocd --type='json' -p='[
                {
                  "op": "replace",
                  "path": "/data/repositories.yaml",
                  "value": "repositories:\n- url: http://gitea-http:3000/ops/homelab.git\n  type: git\n  name: homelab"
                }
              ]'
              
              # Restart ArgoCD repo server to pick up new config
              kubectl rollout restart deployment argocd-repo-server -n argocd
              kubectl rollout status deployment argocd-repo-server -n argocd
              
              echo "ArgoCD repository configuration updated successfully!"