apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: config
        image: golang:1.21-alpine
        command:
        - sh
        - -c
        - |
          cd /app
          go mod tidy
          go run .
        env:
        - name: GITEA_URL
          value: "http://gitea-http:3000"
        - name: GITEA_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitea-admin-secret
              key: username
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-admin-secret
              key: password
        volumeMounts:
        - name: config-source
          mountPath: /app
        - name: config-yaml
          mountPath: /config
      volumes:
      - name: config-source
        configMap:
          name: gitea-config-source
      - name: config-yaml
        configMap:
          name: gitea-config-source