# Copy gitea-credentials secret from postgresql-cluster namespace to gitea namespace
# This allows Gitea to access the database credentials created by the PostgreSQL cluster
---
{{- $secret := lookup "v1" "Secret" "postgresql-cluster" "gitea-credentials" }}
{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: gitea-credentials
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/basic-auth
data:
  username: {{ $secret.data.username }}
  password: {{ $secret.data.password }}
{{- end }}