apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Homelab - Data Platform Architecture</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background-color: #f5f5f5; }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
            .section { margin: 20px 0; padding: 15px; background: #ecf0f1; border-radius: 5px; }
            .status { color: #27ae60; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🏠 Homelab - Data Platform Architecture</h1>
            
            <div class="section">
                <h3>📊 Platform Status</h3>
                <p class="status">✅ Kubernetes Cluster: Running</p>
                <p class="status">✅ ArgoCD: Deployed</p>
                <p class="status">✅ Gitea: Deployed</p>
                <p class="status">✅ Nginx: Running</p>
            </div>
            
            <div class="section">
                <h3>🚀 Services</h3>
                <p><strong>ArgoCD:</strong> <a href="http://localhost:30080" target="_blank">http://localhost:30080</a></p>
                <p><strong>Gitea:</strong> <a href="http://localhost:30300" target="_blank">http://localhost:30300</a></p>
                <p><strong>Nginx:</strong> <a href="http://localhost:30080" target="_blank">http://localhost:30080</a></p>
            </div>
            
            <div class="section">
                <h3>🏗️ Architecture Layers</h3>
                <p><strong>System Layer:</strong> ArgoCD for GitOps management</p>
                <p><strong>Platform Layer:</strong> Gitea for source code management</p>
                <p><strong>Application Layer:</strong> Nginx web server</p>
            </div>
            
            <div class="section">
                <h3>📚 Learning Objectives</h3>
                <p>This homelab demonstrates modern data platform architecture patterns including:</p>
                <ul>
                    <li>GitOps deployment methodology</li>
                    <li>Layered architecture design</li>
                    <li>Container orchestration with Kubernetes</li>
                    <li>Infrastructure as Code</li>
                </ul>
            </div>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  namespace: nginx
  labels:
    app: nginx-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index