apiVersion: v2
name: argocd
description: ArgoCD installation for homelab GitOps
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 8.3.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm