apiVersion: v2
name: argocd
description: ArgoCD with dual repository support
type: application
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 5.46.8
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 1.4.1
    repository: https://argoproj.github.io/argo-helm