argo-cd:
  global:
    domain: argocd.homelab.local
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      resource.ignoreResourceUpdatesEnabled: true
      resource.customizations.ignoreResourceUpdates.all: |
        jsonPointers:
          - /status
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.homelab.local
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  dex:
    enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics

argocd-apps:
  applicationsets:
    - name: root
      namespace: argocd
      generators:
        - git:
            repoURL: https://github.com/satrijandi/homelab
            revision: main
            directories:
              - path: system/*
              - path: platform/*
              - path: apps/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
          project: default
          source:
            repoURL: https://github.com/satrijandi/homelab
            path: '{{path}}'
            targetRevision: main
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
              - ApplyOutOfSyncOnly=true
              - ServerSideApply=true