argo-cd:
  server:
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics

# Disable argocd-apps for initial setup
argocd-apps:
  enabled: false